---
- name: Validate input facts
  ansible.builtin.assert:
    that:
      - opt_openssh_architecture|string in ["32", "64"]

- name: Check if OpenSSH has been downloaded and extracted
  ansible.windows.win_stat:
    path: '{{ opt_openssh_install_path }}\sshd.exe'
  register: pri_openssh_installed

- name: Download and extract the OpenSSH zip
  ansible.builtin.include_tasks: download.yml
  when: not pri_openssh_installed.stat.exists

- name: Create OPENSSH_HOME environment variable
  ansible.windows.win_environment:
    name: OPENSSH_HOME
    level: machine
    state: present
    value: '{{ opt_openssh_install_path }}'

- name: Add OPENSSH_HOME to to system PATH
  ansible.windows.win_path:
    name: PATH
    scope: machine
    state: present
    elements: '%OPENSSH_HOME%'

- name: Setup ssh server components
  ansible.builtin.include_tasks: service.yml
  when: opt_openssh_setup_service
