# setup a single or list of public keys in the current users authorized_keys file
---
- name: Get full path of .ssh directory
  ansible.windows.win_shell: $env:USERPROFILE + "\.ssh"
  changed_when: false
  register: pri_openssh_ssh_dir

  # Get the SID to avoid translation issues down the line - https://github.com/jborean93/ansible-role-win_openssh/issues/11
- name: Get current user SID for ACL
  ansible.windows.win_shell: '[System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value'
  changed_when: false
  register: pri_openssh_ssh_current_user

- name: Ensure the .ssh directory exists for the current user
  ansible.windows.win_file:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    state: directory

- name: Set correct permissions on .ssh directory
  ansible.windows.win_acl:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    user: '{{ item }}'
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
    propagation: None
  with_items:
    - S-1-5-18 # "SYSTEM" group independent of localization
    - S-1-5-32-544 # "Administrators" group independent of localization
    - '{{ pri_openssh_ssh_current_user.stdout_lines[0] }}'

- name: Disable ACL inheritence on .ssh directory
  ansible.windows.win_acl_inheritance:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}'
    reorganize: false
    state: absent

- name: Ensure pubkeys are added to the authorized_keys file
  community.windows.win_lineinfile:
    path: '{{ pri_openssh_ssh_dir.stdout_lines[0] }}\authorized_keys'
    create: true
    line: '{{ item }}'
    state: present
  with_items: '{{ openssh_windows_pubkeys }}'
